Upgrade change: mistake between Install and upgrade
YunoHost-Apps/flarum_ynh pull request #41
Opened 2017-03-04 20:19 UTC by frju365

2017-03-04 20:22 UTC, frju365 commented
for the level 3

2017-03-04 22:48 UTC, frju365 commented
fix upgrade discussed in #8

2017-03-05 18:41 UTC, polytan02 requested changes
En fait c'est le php-fpm.conf qui est "sale". Il faudrait remplacer https://github.com/YunoHost-Apps/flarum_ynh/blob/master/conf/php-fpm.conf#L198 par "chdir = YNH_WWW_ALIAS"
et dans install et upgrade avec le sed rempacer YNH_WWW_ALIAS par $final_path

2017-03-05 18:44 UTC, frju365 commented
bien. Merci.

2017-03-05 18:45 UTC, merged